//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public System.Guid songId { get; set; }
        public string songURL { get; set; }
        public int upvoteCount { get; set; }
        public int downvoteCount { get; set; }
        public Nullable<System.Guid> room_id { get; set; }
        public Nullable<int> queue_order { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
