//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public System.Guid userID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public System.DateTime signupDate { get; set; }
        public Nullable<System.Guid> activeRoom { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
