//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.People = new HashSet<Person>();
            this.Songs = new HashSet<Song>();
        }
    
        public System.Guid roomid { get; set; }
        public bool isPrivate { get; set; }
        public string name { get; set; }
        public Nullable<System.Guid> administrator { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<Song> Songs { get; set; }
    }
}
